name: serrato_water_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  http: ^0.13.3
  equatable: ^2.0.0
  flutter_signature_pad: ^3.0.1
  file_picker: ^5.5.0
  provider: ^6.0.5
  multi_select_flutter: ^4.1.3
  flutter_multiselect: ^1.0.0
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png    

